version: '3'
services:
  sut:
    image: osseus:latest
    env_file: .env
    command: ["pytest", "tests/test_server.py"]

  app:
    image: osseus:latest
    env_file: .env
    expose:
      - 8080
  nginx:
    image: osseus-proxy:latest
    ports:
      - "80:80"
    depends_on:
      - app
