version: '3'
services:
  sut:
    image: osseus:latest
    env_file: server_envvars.env
    command: ["pytest", "tests/test_server.py"]

  server:
    image: osseus:latest
    env_file: server_envvars.env
    ports:
      - "8080:8080"
