version: '3'
services:
  sut:
    image: osseus:latest
    env_file: env/.env
    command: ["bash", "tests/test.sh"]
  app:
    image: osseus:latest
    env_file: env/.env
    ports:
        - "8080:8080"
